# Generated by Django 4.2.16 on 2024-10-26 14:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_alter_useractivity_user"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="notification",
            options={"ordering": ["-timestamp"]},
        ),
        migrations.AlterModelOptions(
            name="useractivity",
            options={
                "ordering": ["-timestamp"],
                "verbose_name_plural": "User Activities",
            },
        ),
        migrations.AlterField(
            model_name="trainingresource",
            name="file",
            field=models.FileField(
                upload_to="training_resources/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        ["pdf", "docx", "pptx"]
                    )
                ],
            ),
        ),
    ]
