# Generated by Django 4.2.16 on 2024-10-31 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0006_userstats"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="role",
            field=models.CharField(
                choices=[
                    ("admin", "Admin"),
                    ("manager", "Manager"),
                    ("employee", "Employee"),
                ],
                default="admin",
                max_length=10,
            ),
        ),
    ]
