# Generated by Django 4.2.16 on 2024-10-26 04:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_remove_product_stock_employee_assigned_shifts_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employee",
            name="hire_date",
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
