# Generated by Django 4.2.16 on 2024-10-31 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pos", "0002_alter_inventory_product"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="mpesa_receipt_number",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="payment",
            name="mpesa_status",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="payment",
            name="mpesa_transaction_id",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
